---
# tasks/main.yml for mysqld_exporter

- name: Create mysqld_exporter user
  ansible.builtin.user:
    name: mysqld_exporter
    shell: /usr/sbin/nologin
    system: yes

- name: Download MySQL exporter archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.{{ arch }}.tar.gz"
    dest: "/tmp/mysqld_exporter.tar.gz"
    mode: '0644'

- name: Unarchive MySQL exporter
  ansible.builtin.unarchive:
    src: "/tmp/mysqld_exporter.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    extra_opts: [ "--strip-components=1" ]
    creates: "/usr/local/bin/mysqld_exporter"

- name: Create directory for mysqld_exporter config
  ansible.builtin.file:
    path: "/etc/prometheus/exporters"
    state: directory
    mode: '0755'

- name: Create MySQL exporter config
  ansible.builtin.template:
    src: "mysqld_exporter.cnf.j2"
    dest: "/etc/prometheus/exporters/mysqld_exporter.cnf"
    owner: mysqld_exporter
    group: mysqld_exporter
    mode: '0600'

- name: Create mysqld_exporter systemd service
  ansible.builtin.template:
    src: "mysqld_exporter.service.j2"
    dest: "/etc/systemd/system/mysqld_exporter.service"
    mode: '0644'
    owner: root
    group: root

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start mysqld_exporter
  ansible.builtin.systemd:
    name: mysqld_exporter
    enabled: true
    state: started
